server:  # should respect identation
  port: 8080
  servlet:
    context-path: /bootcamp


spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: postgres://dnxyvfklcumhsv:0572f7589a11225430e4915daf0b602bb625bdebeb5660c09d1c96aa52ac0a20@ec2-54-90-55-211.compute-1.amazonaws.com:5432/dco7fuh8o2ku0l
      username: dnxyvfklcumhsv
      password: 0572f7589a11225430e4915daf0b602bb625bdebeb5660c09d1c96aa52ac0a20
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      hibernate:
        ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: 1.0
